Remove SecurityManager
smallrye/smallrye-config pull request #1194
Opened 2024-07-04 16:27 UTC by radcortez

2024-07-05 13:51 UTC, dmlloyd commented
Do we know that all downstream consumers (specifically WildFly) are OK with not having security manager support?

2024-07-08 11:22 UTC, darranl requested changes
WildFly is going to need to retain security manager support as long as we are supporting Jakarta EE 10 - this also looks to be submitted to a branch which is producing micro releases, should a removal like this trigger a larger version bump?

2024-07-12 14:42 UTC, radcortez commented
> WildFly is going to need to retain security manager support as long as we are supporting Jakarta EE 10 - this also looks to be submitted to a branch which is producing micro releases, should a removal like this trigger a larger version bump?

We only set the release version on the actual release. Right now, it is just the version generated by Maven. We may consider moving to something like `999-SNAPSHOT` for development like Quarkus.

Ok, let's keep the SecurityManager for a little longer.

2026-08-20 20:40 UTC, radcortez commented
Moving forward with this, since Wildfly 42 is already out:
https://github.com/smallrye/smallrye-common/pull/397#issuecomment-3907695094

2026-08-21 11:49 UTC, merged