fix: avoid out of range error with long profile names
smallrye/smallrye-config pull request #1272
Opened 2024-12-18 09:43 UTC by jeloba

Long profile names, such as `test-with-native-agent` may cause string length overruns on short properties.

This introduces a check to avoid that.

2024-12-19 17:06 UTC, radcortez requested changes
Do you mind creating a test for this? Thank you!

2024-12-20 16:12 UTC, jeloba commented
@radcortez added a test. Before the change it would throw an out of bound exception, not it passes.

2025-01-02 10:24 UTC, radcortez approved these changes

2025-01-02 10:24 UTC, merged

2025-01-02 10:24 UTC, radcortez commented
Excellent. Thank you!