Use application classloader for proxies
smallrye/smallrye-config pull request #419
Opened 2020-10-12 17:15 UTC by tevans78

Signed-off-by: tevans <tevans@uk.ibm.com>

fixes #418

2020-10-13 10:00 UTC, Emily-Jiang commented
Thanks @tevans78 ! @radcortez can you take a look to see whether you have any comments?

2020-10-13 15:25 UTC, radcortez commented
Thank you. Please, open this up to master and I'll rebase. Additional specific changes for the branch can be added later.

2020-10-13 15:30 UTC, radcortez requested changes

2020-10-13 15:38 UTC, tevans78 commented on implementation/src/main/java/io/smallrye/config/ConfigMappingLoader.java
> -    private static Class<?> loadClass(final String className, final byte[] classBytes) {
`defineClass` instead of the second `loadClass` method?

2020-10-13 15:38 UTC, radcortez commented on implementation/src/main/java/io/smallrye/config/ConfigMappingLoader.java
> -    private static Class<?> loadClass(final String className, final byte[] classBytes) {
Yes, just call it `defineClass`.

2020-10-13 16:57 UTC, Emily-Jiang commented
@radcortez do you mean all PRs need to be opened against master and you will rebase the mpconfig20 against master? Just to be clear this change is needed for MP Config 2.0 support for Open Liberty.

2020-10-14 12:06 UTC, radcortez requested changes
Hi @tevans78,

Can you please rebase your commit just with master? We can add the specific code change related with `ConfigMappingClass` after we merge and rebase.

2020-10-14 13:17 UTC, tevans78 commented
@radcortez sure, I haven't had a chance to do anything with this PR yet today ... I have no idea why github thinks I requested a review 2 hours ago?!

2020-10-14 13:30 UTC, radcortez commented
Oh... I thought you did something to it, because I got the review notification, plus the PR had some weird history.

2020-10-14 13:43 UTC, tevans78 commented
@radcortez ready for re-review ;-) many thanks to @Azquelt for doing the rebase for me.

2020-10-14 15:04 UTC, Azquelt commented on implementation/src/main/java/io/smallrye/config/ConfigMappingLoader.java
> -    private static Class<?> loadClass(final String className, final byte[] classBytes) {
I made this change when I did the rebase on `master`

2020-10-14 22:55 UTC, radcortez approved these changes

2020-10-14 22:56 UTC, radcortez commented
Thank you @tevans78 and @Azquelt!

2020-10-14 22:56 UTC, merged